### ISSUE TITLE
Peru province data

### ISSUE THREAD

**Issue by jzamalloa1** [GoogleCloudPlatform/covid-19-open-data#39] opened 2020-08-05 00:18 UTC
Hi,

I noticed some discrepancies with the subregion1 level data in Peru. For example in Madre de Dios and Arequipa the total_ confirmed (and by extension the new_confirmed) cases are much lower than what is reported currently, both are in the 100s, but the total cases in both regions are in the 1000s (according to online reporting). Could you double-check the source please?

Thank you

**Comment by owahltinez** [comment] 2020-08-05 18:27
Thanks for reporting, @jzamalloa1. I can confirm that we are miscounting the cases at the department level. This is probably due to a bug in how we aggregate provinces into departments, but now that the data source added a column for the department name we can easily fix this issue.

**Comment by jzamalloa1** [comment] 2020-08-05 22:49
great, thank you!

**Comment by owahltinez** [comment] 2020-08-06 19:35
This issue appears to be fixed now, thanks again for reporting it.

Here are Arequipa's numbers, much more reasonable looking: https://open-covid-19.github.io/explorer/report/?key=PE_ARE

**Closed** 2020-08-08 17:01 UTC
Labels: bug, help wanted
